### ISSUE TITLE
error with step 11. ansible-inventory config-otnodes-and-cosmic.yml

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-Ansible-Files-and-Playbooks#1]
The command : ansible-inventory config-otnodes-and-cosmic.yml
does not provide any output

Suggestion : 
ansible-inventory --graph
ansible all -m ping
before using ping command, if using SSH keys to log in to nodes, do the following first : 
ssh-agent bash
ssh-add
insert password

**Comment by calr0x** [comment]
This is good stuff...

**Comment by calr0x** [comment]
Applied!
