### ISSUE TITLE
improvements to node_config.json

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-Ansible-Files-and-Playbooks#2]
Suggested config file format : 
{
        "network": {
        "hostname": "IP_OF_YOUR_SERVER",
        "remoteWhitelist": ["127.0.0.1"]
        },
        "initial_deposit_amount": "INITIAL_DEPOSIT_AMOUNT_HERE",
        "dataset_pruning": {
           "enabled": true,
           "imported_pruning_delay_in_minutes": 1440,
           "replicated_pruning_delay_in_minutes": 1440
        },
        "blockchain": {
        "implementations": [
                {
                "blockchain_title": "xDai",
                "network_id": "xdai:mainnet",
                "node_wallet": "PUBLIC_KEY_OF_YOUR_WALLET",
                "node_private_key": "PRIVATE_KEY_OF_YOUR_WALLET",
                "management_wallet": "PUBLIC_KEY_OF_MANAGEMENT_WALLET",
                "dh_price_factor" : "DH_PRICE_FACTOR",
	              "dh_max_holding_time_in_minutes" : "DH_HOLDING_TIME_MINUTES",
                "disable_auto_payouts" : "false"
                }
        ]
        }
}

Modifications : 
added dataset_pruning
changed disable_auto_payouts to false

**Comment by calr0x** [comment]
Thanks! Will do!
