### ISSUE TITLE
forever scripts on install-complete.yml

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-Ansible-Files-and-Playbooks#3]
Suggestion : 
do not start cosmic forever scripts as the backup and ping will "interfere" with NodeWatch and OT-Smoothbrain-Backup, at least only disable these two

**Comment by calr0x** [comment]
I'm going to have the following happen:

1. If using Ansible to install Smoothbrain/NodeWatch look for conflicting Cosmic scripts.
2. Warnings in readme's for both projects manual installs to disable those scripts.

**Comment by calr0x** [comment]
Applied!

Both Smoothbrain-Backup and NodeWatch ansible installs will now disable the appropriate Cosmic scripts upon installation! I will still need to add manual directions for those as well
