### ISSUE TITLE
[SOLUTION] /usr/bin/python: not found

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-Ansible-Files-and-Playbooks#5]
Context :
I am deploying ansible on a raspberry pi 3B+ using Python2 and the following error came up when using ansible myserver -m ping : 
xx.xx.xx.xx | FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to xx.xx.xx.xx closed.\r\n",
    "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 127
}

Reasoning : 
Our local server is using Python2 (as indicated by location /usr/bin/python or using python --version) but remote server requires Python3. Ansible must use Python3 to deploy on our playbooks.

Solution : 
If all remote hosts definitely have Python3, you can just add the variable to group_vars/all.yml file : 
1. Navigate to your project folder
cd /etc/ansible
2. Create the directory if not already there
mkdir group_vars
3. Create the .yml file for the fix
nano group_vars/all
4. Add the fix inside
ansible_python_interpreter: /usr/bin/python3

if you try 'ansible xx.xx.xx.xx -m ping' again, you should be able to connect

**Comment by calr0x** [comment]
I believe this is on your pi and not on the servers (which should all have python3 already. We might just make a note for those running an old OS on their control computer add python3 and apply your fix...
