### ISSUE TITLE
Daily Docker Restart

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-Ansible-Files-and-Playbooks#6]
I suggest Ansible has a daily docker restart just in case the nodes needed it, keeping them ticking along with less manual management.

It could be a contab thing.

Suggest either a restart: docker restart otnode
Or a stop start: docker stop otnode
docker start otnode

**Comment by hottogo** [comment]
Reboot daily scheduled may also be very handy, reboot fixed an issue for me this week.

**Comment by calr0x** [comment]
> Reboot daily scheduled may also be very handy, reboot fixed an issue for me this week.

I will add a playbook for each separately!

**Comment by calr0x** [comment]
Both added!
